# Simple workflow for deploying static content to GitHub Pages
name: test

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "test"
  cancel-in-progress: false

jobs:
  # single deploy job since we're just deploying
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: serve
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: tunnel
        run: |
          wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
          unzip ./ngrok*.zip
          mv ngrok tmp/
          export NGROK_AUTHTOKEN=${{ secrets.NGROK_AUTHTOKEN }}
          nohup tmp/ngrok http 3000 &
      - run: |
          export RAILS_ENV=production
          bundle
          bundled exec rails db:migrate
          bundled exec rails server
